# Generated by Django 4.0.5 on 2022-06-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciboulexp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='UNDEF', max_length=200)),
                ('xpid', models.CharField(default='UNDEF', max_length=200)),
                ('json', models.TextField(blank=True)),
                ('xpinfo', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciboulai.ciboulexp')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpid', models.CharField(default='UNDEF', max_length=200)),
                ('task', models.CharField(default='UNDEF', max_length=200)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNDEF', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmapReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainCycle', models.CharField(default='UNDEF', max_length=200)),
                ('ciboulexp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciboulai.ciboulexp')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonTask', models.TextField(blank=True)),
                ('symbol', models.CharField(default='NAN', max_length=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciboulai.ciboulexp')),
                ('taskRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciboulai.task')),
            ],
            options={
                'unique_together': {('taskRef', 'expRef')},
            },
        ),
    ]
