# Generated by Django 3.2.9 on 2022-10-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciboulai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciboulexp',
            table='main_ciboulexp',
        ),
        migrations.AlterModelTable(
            name='gmapreference',
            table='main_gmapreference',
        ),
        migrations.AlterModelTable(
            name='note',
            table='main_note',
        ),
        migrations.AlterModelTable(
            name='task',
            table='main_task',
        ),
        migrations.AlterModelTable(
            name='taskinstance',
            table='main_taskinstance',
        ),
    ]
